[package]
name = "test-module"
version = "0.0.0"
edition = "2024"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rem = { path = ".." }

[dev-dependencies]
test-cdylib = { version = "1.1.0", default-features = false }

[features]
bindgen = ["rem/bindgen"]
