on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - "**/*.rs"
      - "**/*.el"
      - "Cargo.*"
      - "Makefile.in"
      - "configure*"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        include:
          - host: ubuntu-latest
          - host: windows-latest
          - host: macos-latest
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - if: runner.os == 'Windows'
        run:
          cargo test
      - uses: jcs090218/setup-emacs@v3
        if: runner.os != 'Windows'
        with:
          version: 30.1
      - name: Test
        shell: bash
        if: runner.os != 'Windows'
        run: |
          ./configure CARGOPROFILE=debug
          make check
